---

  - hosts: localhost
    become_user: root
    tasks: 
      - name: "Install git, python tools, and mysql"
        become: yes
        yum: 
          name: 
            - community-mysql-server
            - git
            - python-setuptools
            - pip
    
      - name: Resart mysqld
        become: yes
        service: 
          name: mysqld 
          state: restarted

      - name: "Install PyMySQL python module via pip"
        become: yes 
        pip: 
          # extra_args: "--user {{ controller.user }}"
          name: PyMySQL
    
      - name: "Create and configure mysql users"
        become: yes
        mysql_user: 
          login_host: root
          password: "{{ mysql.root_password }}"
        mysql_user: 
          name: "{{ mysql.username }}"
          password: "{{ mysql.password }}"
          priv: "*.*:ALL"
          state: present

      - name: "print env vars"
        debug: 
          msg: "{{ lookup('env','VENV','ANSIBLE_COLLECTIONS_PATHS') }}"

      - name: "export venv and export collections"
        shell: 
          chdir: /opt/stack/bifrost
          cmd: bash ./scripts/env-setup.sh
        
      - name: "source stuff"
        shell: 
          chdir: /opt/stack/bifrost
          cmd: source /opt/stack/bifrost/bin/activate
